enum AppEnvironment { DEV, STAGING, PRODUCTION, SDA, BHARATINTL, MONTFORT, MARIAM,
  NEWCENTURY, AGATHIYA, STANNES, SSM, STANTONYS, NSVV, STMICHELS, STANNESBANGLORE,
  MCA, MONTFORTTINDIVANAM,ARYAN,BHARATHIENGLISHSCHOOL,SUBRAMANIABHARATHISCHOOL,
}
